version: '3.7'

services:
  web:
    build: .
    command:
      - "python"
      - "/code/manage.py"
      - "runserver"
      - "0.0.0.0:8000"
      - "gunicorn"
      - "primeclimatecare_project.wsgi"
      - "-b"
      - "0.0.0.0:8000"
    environment:
      - ENVIRONMENT=production
      - SECRET_KEY=p%2(?Hx*6k5Z6b.qe*_mS.5&&"JB;"SasIoCFrpma:P{/gM@lz
      - DEBUG=0
      - STRIPE_TEST_PUBLISHABLE_KEY=pk_test_51OMgDSFeXq7ASkEgwrGny3Jem8iCrSikS7ZsM6HxtK12FAjYwy9LmTEyQi2OsfMgBhFozJGTdlqh9T61RVCkkMjw00Oz7nQzAk
      - STRIPE_TEST_SECRET_KEY=sk_test_51OMgDSFeXq7ASkEgVU2eTupAGV1CxmNkiZapqXMXLBL8bzcqN2mFHM2XJqjg6Sam6X2oX3RUNyCXqfmWrzW9NqQJ00Avv3GiW4
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:16
    environment:
        - POSTGRES_PASSWORD=postgres