version: '3.7'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    environment:
      - SECRET_KEY=django-insecure-fs(_74+6)1tykcxb%-c^knsik#m6&3_yhnnv)t8ys%jj5*71c+
      - DEBUG=1
      - STRIPE_TEST_PUBLISHABLE_KEY=pk_test_51OMgDSFeXq7ASkEgwrGny3Jem8iCrSikS7ZsM6HxtK12FAjYwy9LmTEyQi2OsfMgBhFozJGTdlqh9T61RVCkkMjw00Oz7nQzAk
      - STRIPE_TEST_SECRET_KEY=sk_test_51OMgDSFeXq7ASkEgVU2eTupAGV1CxmNkiZapqXMXLBL8bzcqN2mFHM2XJqjg6Sam6X2oX3RUNyCXqfmWrzW9NqQJ00Avv3GiW4
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:16
    environment:
        - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/


volumes:
  postgres_data: